export const DIALOG_TYPE = {
  ADMIN_USER_EDIT: "ADMIN_USER_EDIT",
  ADMIN_USER_DELETE: "ADMIN_USER_DELETE",
  ADMIN_REQUEST_APPROVE: "ADMIN_REQUEST_APPROVE",
  ADMIN_REQUEST_DECLINE: "ADMIN_REQUEST_DECLINE",
  SHOP_DELETE: "SHOP_DELETE",
  PRODUCT_DELETE: "PRODUCT_DELETE",
  AVATAR_EDIT: "AVATAR_EDIT",
};
