export const permissionRules = {
  MANAGE_DASHBOARD: "MANAGE_DASHBOARD",
  MANAGE_USER: "MANAGE_USER",
  READ_SHOP: "READ_SHOP",
  CREATE_SHOP: "CREATE_SHOP",
  READ_ORDER: "READ_ORDER",
  MANAGE_CART: "MANAGE_CART",
};
